name: Build and Push Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v4

      - name: 🐳 Docker Build
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/nginx-pramhas:latest .

      - name: 🔐 Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: 📤 Docker Push
        run: docker push ${{ secrets.DOCKER_USERNAME }}/nginx-pramhas:latest
